version: '3'
services:
  # dbt:
  #   image: ghcr.io/dbt-labs/dbt-postgres:1.7.17
  #   command:
  #     [
  #       "run",
  #       "--profiles-dir",
  #       "/root",
  #       "--project-dir",
  #       "/dbt",
  #       "--full-refresh"
  #     ]
  #   networks:
  #     - elt_network
  #   volumes:
  #     - ./custom_postgres:/dbt
  #     - ./.dbt:/root
  #   depends_on:
  #     elt_script:
  #       condition : service_completed_successfully
  #   environment:
  #     DBT_PROFILE: default
  #     DBT_TARGET: dev
networks:
  elt_network:
    driver: bridge